language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install pkg-config texinfo texlive
script: autoreconf --install && ./configure --enable-timeout-tests=no && make check
